export const windowsToIana = {
    'Afghanistan Standard Time': 'Asia/Kabul',
    'Central Europe Standard Time': 'Europe/Belgrade',
    'UTC-11': 'Pacific/Pago_Pago',
    'W. Europe Standard Time': 'Europe/Amsterdam',
    'Argentina Standard Time': 'America/Argentina/Buenos_Aires',
    'Caucasus Standard Time': 'Asia/Yerevan',
    'AUS Eastern Standard Time': 'Australia/Sydney',
    'Azerbaijan Standard Time': 'Asia/Baku',
    'Arab Standard Time': 'Asia/Riyadh',
    'Bangladesh Standard Time': 'Asia/Dhaka',
    'Belarus Standard Time': 'Europe/Minsk',
    'Atlantic Standard Time': 'America/Halifax',
    'South Africa Standard Time': 'Africa/Johannesburg',
    'UTC': 'UTC',
    'E. South America Standard Time': 'America/Sao_Paulo',
    'Central Asia Standard Time': 'Asia/Almaty',
    'Singapore Standard Time': 'Asia/Singapore',
    'Cape Verde Standard Time': 'Atlantic/Cape_Verde',
    'SE Asia Standard Time': 'Asia/Bangkok',
    'Eastern Standard Time': 'America/New_York',
    'Pacific SA Standard Time': 'America/Santiago',
    'China Standard Time': 'Asia/Shanghai',
    'Myanmar Standard Time': 'Asia/Yangon',
    'Hawaiian Standard Time': 'Pacific/Honolulu',
    'Greenwich Standard Time': 'Africa/Abidjan',
    'Central European Standard Time': 'Europe/Belgrade',
    'E. Europe Standard Time': 'Europe/Kiev',
    'Tokyo Standard Time': 'Asia/Tokyo',
    'Romance Standard Time': 'Europe/Paris',
    'SA Western Standard Time': 'America/La_Paz',
    'SA Pacific Standard Time': 'America/Lima',
    'Egypt Standard Time': 'Africa/Cairo',
    'Central America Standard Time': 'America/Belize',
    'W. Central Africa Standard Time': 'Africa/Algiers',
    'E. Africa Standard Time': 'Africa/Nairobi',
    'SA Eastern Standard Time': 'America/Cayenne',
    'GMT Standard Time': 'Europe/London',
    'Fiji Standard Time': 'Pacific/Fiji',
    'FLE Standard Time': 'Europe/Helsinki',
    'West Asia Standard Time': 'Asia/Tashkent',
    'Georgian Standard Time': 'Asia/Tbilisi',
    'GTB Standard Time': 'Europe/Athens',
    'Greenland Standard Time': 'America/Nuuk',
    'West Pacific Standard Time': 'Pacific/Guam',
    'Mauritius Standard Time': 'Indian/Mauritius',
    'India Standard Time': 'Asia/Kolkata',
    'Arabic Standard Time': 'Asia/Baghdad',
    'Iran Standard Time': 'Asia/Tehran',
    'Israel Standard Time': 'Asia/Tel_Aviv',
    'Jordan Standard Time': 'Asia/Amman',
    'UTC+12': 'Pacific/Tarawa',
    'Korea Standard Time': 'Asia/Seoul',
    'Middle East Standard Time': 'Asia/Beirut',
    'Central Standard Time (Mexico)': 'America/Mexico_City',
    'Ulaanbaatar Standard Time': 'Asia/Ulaanbaatar',
    'Morocco Standard Time': 'Africa/Casablanca',
    'Namibia Standard Time': 'Africa/Windhoek',
    'Central Pacific Standard Time': 'Pacific/Noumea',
    'New Zealand Standard Time': 'Pacific/Auckland',
    'Nepal Standard Time': 'Asia/Kathmandu',
    'Arabian Standard Time': 'Asia/Dubai',
    'Pakistan Standard Time': 'Asia/Karachi',
    'Paraguay Standard Time': 'America/Asuncion',
    'Pacific Standard Time': 'America/Los_Angeles',
    'Russian Standard Time': 'Europe/Moscow',
    'Samoa Standard Time': 'Pacific/Apia',
    'UTC-02': 'America/Noronha',
    'Sri Lanka Standard Time': 'Asia/Colombo',
    'Syria Standard Time': 'Asia/Damascus',
    'Taipei Standard Time': 'Asia/Taipei',
    'Tonga Standard Time': 'Pacific/Tongatapu',
    'Türkiye Standard Time': 'Europe/Istanbul',
    'Mountain Standard Time': 'America/Denver',
    'Montevideo Standard Time': 'America/Montevideo',
    'Venezuela Standard Time': 'America/Caracas'
}